base/urls.py
from django.urls import path, include, reverse_lazy

from .views import DmScreenTabList, DmScreenTabAdd, DmScreenTabDetail, DmScreenTabEdit, DmScreenTabDelete

from _config.urls import breadcrumbs

dmscreen_breadcrumbs = breadcrumbs + [{'href': reverse_lazy('dmscreentabs-home'), 'text': 'DM Screen Tabs'}]

dmscreen_patterns = [
    path('', DmScreenTabList.as_view(), name='dmscreentabs-home'),
    path('add/', DmScreenTabAdd.as_view(), name='dmscreentab-add'),
    path('<int:pk>/', DmScreenTabDetail.as_view(), name='dmscreentab-view'),
    path('<int:pk>/edit/', DmScreenTabEdit.as_view(), name='dmscreentab-edit'),
    path('<int:pk>/delete/', DmScreenTabDelete.as_view(), name='dmscreentab-delete'),
]

urlpatterns = [
    path('dm-screen-tabs/', include(dmscreen_patterns), {'base_breadcrumbs': dmscreen_breadcrumbs}),
]

statblocks/urls.py
from django.urls import path, include, reverse_lazy

from .views import \
    MonsterList, MonsterAdd, MonsterDetail, MonsterEdit, MonsterDelete, MonsterAutocomplete, \
    SpecialPropertyList, SpecialPropertyAdd, SpecialPropertyDetail, SpecialPropertyEdit, SpecialPropertyDelete, SpecialPropertyAutocomplete, \
    ActionList, ActionAdd, ActionDetail, ActionEdit, ActionDelete, ActionAutocomplete, \
    LegendaryActionList, LegendaryActionAdd, LegendaryActionDetail, LegendaryActionEdit, LegendaryActionDelete, LegendaryActionAutocomplete, \
    ReactionList, ReactionAdd, ReactionDetail, ReactionEdit, ReactionDelete, ReactionAutocomplete

from _config.urls import breadcrumbs

monsters_breadcrumbs = breadcrumbs + [{'href': reverse_lazy('monsters-home'), 'text': 'Monsters'}]

monsters_patterns = [
    path('', MonsterList.as_view(), name='monsters-home'),
    path('add/', MonsterAdd.as_view(), name='monster-add'),
    path('<int:pk>/', MonsterDetail.as_view(), name='monster-view'),
    path('<int:pk>/edit/', MonsterEdit.as_view(), name='monster-edit'),
    path('<int:pk>/delete/', MonsterDelete.as_view(), name='monster-delete'),
]

specialprop_breadcrumbs = breadcrumbs + [{'href': reverse_lazy('specialproperties-home'), 'text': 'Monster Special Properties'}]

specialprop_patterns = [
    path('', SpecialPropertyList.as_view(), name='specialproperties-home'),
    path('add/', SpecialPropertyAdd.as_view(), name='specialproperty-add'),
    path('<int:pk>/', SpecialPropertyDetail.as_view(), name='specialproperty-view'),
    path('<int:pk>/edit/', SpecialPropertyEdit.as_view(), name='specialproperty-edit'),
    path('<int:pk>/delete/', SpecialPropertyDelete.as_view(), name='specialproperty-delete'),
]

action_breadcrumbs = breadcrumbs + [{'href': reverse_lazy('actions-home'), 'text': 'Monster Actions'}]

action_patterns = [
    path('', ActionList.as_view(), name='actions-home'),
    path('add/', ActionAdd.as_view(), name='action-add'),
    path('<int:pk>/', ActionDetail.as_view(), name='action-view'),
    path('<int:pk>/edit/', ActionEdit.as_view(), name='action-edit'),
    path('<int:pk>/delete/', ActionDelete.as_view(), name='action-delete'),
]

legaction_breadcrumbs = breadcrumbs + [{'href': reverse_lazy('legendaryactions-home'), 'text': 'Monster Legendary Actions'}]

legaction_patterns = [
    path('', LegendaryActionList.as_view(), name='legendaryactions-home'),
    path('add/', LegendaryActionAdd.as_view(), name='legendaryaction-add'),
    path('<int:pk>/', LegendaryActionDetail.as_view(), name='legendaryaction-view'),
    path('<int:pk>/edit/', LegendaryActionEdit.as_view(), name='legendaryaction-edit'),
    path('<int:pk>/delete/', LegendaryActionDelete.as_view(), name='legendaryaction-delete'),
]

reaction_breadcrumbs = breadcrumbs + [{'href': reverse_lazy('reactions-home'), 'text': 'Monster Reactions'}]

reaction_patterns = [
    path('', ReactionList.as_view(), name='reactions-home'),
    path('add/', ReactionAdd.as_view(), name='reaction-add'),
    path('<int:pk>/', ReactionDetail.as_view(), name='reaction-view'),
    path('<int:pk>/edit/', ReactionEdit.as_view(), name='reaction-edit'),
    path('<int:pk>/delete/', ReactionDelete.as_view(), name='reaction-delete'),
]

autocomplete_patterns = [
    path('special-property/', SpecialPropertyAutocomplete.as_view(create_field='name'), name='specialproperty-autocomplete'),
    path('action/', ActionAutocomplete.as_view(create_field='name'), name='action-autocomplete'),
    path('legendary-action/', LegendaryActionAutocomplete.as_view(create_field='name'), name='legendaryaction-autocomplete'),
    path('reaction/', ReactionAutocomplete.as_view(create_field='name'), name='reaction-autocomplete'),
    path('monster/', MonsterAutocomplete.as_view(), name='monster-autocomplete'),
]

urlpatterns = [
    path('monsters/', include(monsters_patterns), {'base_breadcrumbs': monsters_breadcrumbs}),
    path('monster-properties/', include(specialprop_patterns), {'base_breadcrumbs': specialprop_breadcrumbs}),
    path('monster-actions/', include(action_patterns), {'base_breadcrumbs': action_breadcrumbs}),
    path('monster-legendary-actions/', include(legaction_patterns), {'base_breadcrumbs': legaction_breadcrumbs}),
    path('monster-reactions/', include(reaction_patterns), {'base_breadcrumbs': reaction_breadcrumbs}),
    path('autocomplete/', include(autocomplete_patterns)),
]

statblocks/models.py
from random import randint
from dal import autocomplete
from django.db import models
from django.forms import ModelForm

from multiselectfield import MultiSelectField

from base.models import BaseModel
from base.utils import Size, Alignment, Die, DamageType, Condition, Language, AbilityScore


class Monster(BaseModel):
    generic_name = models.CharField(max_length=255, null=True, blank=True,
                                    help_text="If not specified, the name in lowercase will be used.")
    size = models.IntegerField(choices=Size.MODEL_CHOICES, null=True, blank=True)
    type = models.CharField(max_length=255, null=True, blank=True)
    alignment = models.IntegerField(choices=Alignment.MODEL_CHOICES, null=True, blank=True)
    armor_class = models.IntegerField(null=True, blank=True)
    armor_kind = models.CharField(max_length=255, null=True, blank=True)
    hit_points = models.IntegerField(null=True, blank=True)
    num_hit_die = models.IntegerField(null=True, blank=True)
    hit_die_size = models.IntegerField(choices=Die.MODEL_CHOICES, null=True, blank=True)
    speed = models.CharField(max_length=100, null=True, blank=True)
    str = models.IntegerField(null=True, blank=True)
    dex = models.IntegerField(null=True, blank=True)
    con = models.IntegerField(null=True, blank=True)
    int = models.IntegerField(null=True, blank=True)
    wis = models.IntegerField(null=True, blank=True)
    cha = models.IntegerField(null=True, blank=True)
    proficiency = models.IntegerField(null=True, blank=True)

    @property
    def str_mod(self):
        if self.str:
            return (self.str - 10) // 2
        else:
            return -5

    @property
    def dex_mod(self):
        if self.dex:
            return (self.dex - 10) // 2
        else:
            return -5

    @property
    def con_mod(self):
        if self.con:
            return (self.con - 10) // 2
        else:
            return -5

    @property
    def int_mod(self):
        if self.int:
            return (self.int - 10) // 2
        else:
            return -5

    @property
    def wis_mod(self):
        if self.wis:
            return (self.wis - 10) // 2
        else:
            return -5

    @property
    def cha_mod(self):
        if self.cha:
            return (self.cha - 10) // 2
        else:
            return -5

    saving_throws = models.CharField(max_length=50, null=True, blank=True)
    skills = models.CharField(max_length=255, null=True, blank=True)
    damage_vulnerabilities = MultiSelectField(choices=DamageType.MODEL_CHOICES, null=True, blank=True)
    damage_resistances = MultiSelectField(choices=DamageType.MODEL_CHOICES, null=True, blank=True)
    damage_immunities = MultiSelectField(choices=DamageType.MODEL_CHOICES, null=True, blank=True)
    condition_immunities = MultiSelectField(choices=Condition.MODEL_CHOICES, null=True, blank=True)
    senses = models.CharField(max_length=255, null=True, blank=True)
    languages = MultiSelectField(choices=Language.MODEL_CHOICES, null=True, blank=True)
    challenge = models.CharField(
        max_length=3,
        choices=[
            '0', '1/8', '1/4', '1/2'
        ].extend(['{}'.format(num) for num in range(1, 31)]),
        null=True, blank=True
    )

    special_properties = models.ManyToManyField('statblocks.SpecialProperty', blank=True)
    actions = models.ManyToManyField('statblocks.Action', blank=True)
    legendary_actions = models.ManyToManyField('statblocks.LegendaryAction', blank=True)
    reactions = models.ManyToManyField('statblocks.Reaction', blank=True)

    @property
    def rand_hp(self):
        hp = 0
        for _ in range(self.num_hit_die):
            hp += max(randint(1, self.hit_die_size) + self.con_mod, 1)
        return hp

    @property
    def avg_hp(self):
        con_mod_piece = self.num_hit_die * self.con_mod
        hit_die_avg = (self.hit_die_size + 1) / 2.0
        hit_die_piece = self.num_hit_die * hit_die_avg // 1
        return max(int(con_mod_piece + hit_die_piece), 1)

    @property
    def statblock_generic_name(self):
        if self.generic_name:
            return self.generic_name
        else:
            return self.name.lower()


class StatblockBit(BaseModel):
    class Meta:
        abstract = True

    statblock_title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    sort_priority = models.IntegerField(default=0)
    save_dc = models.IntegerField(null=True, blank=True)
    save_type = models.CharField(max_length=3, choices=AbilityScore.MODEL_CHOICES, null=True, blank=True)

    @property
    def title(self):
        if self.statblock_title:
            return self.statblock_title
        else:
            return self.name

    @property
    def monsters_with(self):
        if hasattr(self, 'monster_set'):
            return str(len(self.monster_set.all()))
        else:
            return '0'


class SpecialProperty(StatblockBit):
    class Meta:
        ordering = ['-sort_priority']


class Action(StatblockBit):

    MELEE_WEAPON_ATTACK = 1
    RANGED_WEAPON_ATTACK = 2
    MELEE_SPELL_ATTACK = 3
    RANGED_SPELL_ATTACK = 4
    ATTACK_TYPE_CHOICES = [
        (MELEE_WEAPON_ATTACK, 'melee weapon attack'),
        (RANGED_WEAPON_ATTACK, 'ranged weapon attack'),
        (MELEE_SPELL_ATTACK, 'melee spell attack'),
        (RANGED_SPELL_ATTACK, 'ranged spell attack'),
    ]

    attack_type = models.IntegerField(choices=ATTACK_TYPE_CHOICES, null=True, blank=True)
    attack_uses = models.CharField(max_length=3, choices=AbilityScore.MODEL_CHOICES, null=True, blank=True, verbose_name='ability score used')
    attack_tohit_bonus_override = models.IntegerField(null=True, blank=True, verbose_name='to-hit bonus')
    reach_range = models.IntegerField(choices=[(5 * num, '{} ft.'.format(5 * num)) for num in range(120)], null=True,
                                      blank=True, verbose_name='reach or first range increment')
    range_secondary = models.IntegerField(choices=[(5 * num, '{} ft.'.format(5 * num)) for num in range(120)],
                                          null=True, blank=True, verbose_name='second range increment')
    num_targets = models.IntegerField(null=True, blank=True, verbose_name='number of targets')
    hit_num_damage_dice = models.IntegerField(null=True, blank=True, verbose_name='number of damage dice')
    hit_type_damage_dice = models.IntegerField(choices=Die.MODEL_CHOICES, null=True, blank=True, verbose_name='damage die')
    hit_damage_type = models.IntegerField(choices=DamageType.MODEL_CHOICES, null=True, blank=True, verbose_name='damage type')
    hit_addl_num_damage_dice = models.IntegerField(null=True, blank=True, verbose_name='number of damage dice (secondary)')
    hit_addl_type_damage_dice = models.IntegerField(choices=Die.MODEL_CHOICES, null=True, blank=True, verbose_name='damage die (secondary)')
    hit_addl_damage_type = models.IntegerField(choices=DamageType.MODEL_CHOICES, null=True, blank=True, verbose_name='damage type (secondary)')

    class Meta:
        ordering = ['-sort_priority']


class LegendaryAction(StatblockBit):
    class Meta:
        ordering = ['-sort_priority']


class Reaction(StatblockBit):
    class Meta:
        ordering = ['-sort_priority']


class MonsterForm(ModelForm):
    class Meta:
        model = Monster
        fields = '__all__'
        widgets = {
            'special_properties': autocomplete.ModelSelect2Multiple(url='specialproperty-autocomplete'),
            'actions': autocomplete.ModelSelect2Multiple(url='action-autocomplete'),
            'legendary_actions': autocomplete.ModelSelect2Multiple(url='legendaryaction-autocomplete'),
            'reactions': autocomplete.ModelSelect2Multiple(url='reaction-autocomplete'),
        }


class SpecialPropertyForm(ModelForm):
    class Meta:
        model = SpecialProperty
        fields = '__all__'


class ActionForm(ModelForm):
    class Meta:
        model = Action
        fields = '__all__'


class LegendaryActionForm(ModelForm):
    class Meta:
        model = LegendaryAction
        fields = '__all__'


class ReactionForm(ModelForm):
    class Meta:
        model = Reaction
        fields = '__all__'

statblocks/templates/statblocks/_monsterquality_detail.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container">
    <div class="card" style="width: 40rem">
      <div class="card-header bg-secondary text-white">
        <div class="d-flex justify-content-between">
          <h4>{{ object.name }}</h4>
          <a class="btn btn-outline-light align-middle" href="{{ object.get_edit_url }}">
            Edit
          </a>
        </div>
      </div>
      <div class="card-body">
        {% block statblock_rendered_text %}{% endblock %}
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item bg-secondary text-white">Monsters with {{ object.name }}</li>
        {% for monster in object.monster_set.all %}
          <a class="list-group-item list-group-item-action"
             href="{{ monster.get_absolute_url }}">{{ monster.name }}
          </a>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

statblocks/templates/statblocks/action.html
{% load base %}
{% load humanize %}

<p class="card-text">
  <strong><em>
    <a class="text-dark" href="{{ object.get_absolute_url }}">
      {{ object.title }}.</a>
  </em></strong>
  {% if object.attack_type %}
    <em>{{ object.get_attack_type_display|title }}:</em>
    {% if object.attack_tohit_bonus_override %}
      +{{ object.attack_tohit_bonus_override }}
    {% elif monster %}
      +{% get_attack_to_hit_for_monster object monster %}
    {% else %}
      +?
    {% endif %}
    to hit,
    {{ object|range_or_reach_text }},
    {{ object.num_targets|apnumber }} target{{ object.num_targets|pluralize }}.
    {% if monster %}
      <em>Hit:</em>
      {% avg_with_die_in_parens object.hit_num_damage_dice object.hit_type_damage_dice monster|get_mod:object.attack_uses %}
    {% else %}
      <em>Hit:</em> {% avg_with_die_in_parens object.hit_num_damage_dice object.hit_type_damage_dice %}
    {% endif %}
    {{ object.get_hit_damage_type_display }} damage{% if not object.hit_addl_num_damage_dice %}.
    {% else %}
      plus
      {% avg_with_die_in_parens object.hit_addl_num_damage_dice object.hit_addl_type_damage_dice %}
      {{ object.get_hit_addl_damage_type_display }} damage.
    {% endif %}
  {% endif %}
  {% if monster %}
    <span style="white-space: pre-line;">{{ object.description|replace_generic_monster:monster }}</span>
  {% else %}
    <span style="white-space: pre-line;">{{ object.description }}</span>
  {% endif %}
</p>

statblocks/templates/statblocks/action_detail.html
{% extends 'statblocks/_monsterquality_detail.html' %}

{% block statblock_rendered_text %}
  {% include 'statblocks/action.html' %}
{% endblock %}

statblocks/templates/statblocks/action_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}
  {% if object %}
    Edit {{ object.name }}
  {% else %}
    Add {{ model.meta.verbose_name }}
  {% endif %}
{% endblock %}

{% block custom_styles %}
  <style>
    #is-attack:not(.active) ~ .attack-only {
      display: none;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="container mb-5">
    <form method="post" action="
    {% if object.pk %}
      {% url form_action pk=object.pk %}
    {% else %}
      {% url form_action %}
    {% endif %}
  ">
      {% csrf_token %}

      <div class="form-row">
        <div class="form-group col-sm">
          {{ form.name.label_tag }}
          {{ form.name|add_class:'form-control'|attr:'autofocus' }}
        </div>
        <div class="form-group col-sm">
          {{ form.statblock_title.label_tag }}
          {{ form.statblock_title|add_class:'form-control' }}
        </div>
      </div>

      <button type="button"
              id="is-attack"
              class="btn btn-outline-dark btn-block mb-3{% if object.attack_type %} active{% endif %}"
              data-toggle="button"
              aria-pressed="{% if object.attack_type %}true{% else %}false{% endif %}">
        Show attack-only fields
      </button>
      <div class="attack-only">
        <div class="form-row">
          <div class="form-group col-sm">
            {{ form.attack_type.label_tag }}
            {{ form.attack_type|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.attack_uses.label_tag }}
            {{ form.attack_uses|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.attack_tohit_bonus_override.label_tag }}
            {{ form.attack_tohit_bonus_override|add_class:'form-control' }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-sm">
            {{ form.reach_range.label_tag }}
            {{ form.reach_range|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.range_secondary.label_tag }}
            {{ form.range_secondary|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.num_targets.label_tag }}
            {{ form.num_targets|add_class:'form-control' }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-sm">
            {{ form.hit_num_damage_dice.label_tag }}
            {{ form.hit_num_damage_dice|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.hit_type_damage_dice.label_tag }}
            {{ form.hit_type_damage_dice|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.hit_damage_type.label_tag }}
            {{ form.hit_damage_type|add_class:'form-control' }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-sm">
            {{ form.hit_addl_num_damage_dice.label_tag }}
            {{ form.hit_addl_num_damage_dice|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.hit_addl_type_damage_dice.label_tag }}
            {{ form.hit_addl_type_damage_dice|add_class:'form-control' }}
          </div>
          <div class="form-group col-sm">
            {{ form.hit_addl_damage_type.label_tag }}
            {{ form.hit_addl_damage_type|add_class:'form-control' }}
          </div>
        </div>
      </div>
      <div class="form-group">
        {{ form.description.label_tag }}
        {{ form.description|add_class:'form-control' }}
      </div>

      <div class="form-row">
        <div class="form-group col-sm">
          {{ form.sort_priority.label_tag }}
          {{ form.sort_priority|add_class:'form-control' }}
        </div>
        <div class="form-group col-sm">
          {{ form.save_dc.label_tag }}
          {{ form.save_dc|add_class:'form-control' }}
        </div>
        <div class="form-group col-sm">
          {{ form.save_type.label_tag }}
          {{ form.save_type|add_class:'form-control' }}
        </div>
      </div>

      {% if object %}
        <a class="btn btn-secondary" href="{{ object.get_absolute_url }}">Cancel</a>
        <a class="btn btn-outline-danger" href="{{ object.get_delete_url }}">Delete {{ object.name }}</a>
      {% endif %}
      <input type="submit" class="btn btn-primary" value="Save"/>
    </form>
  </div>
{% endblock %}

statblocks/templates/statblocks/legendaryaction.html
{% extends 'statblocks/statblockbit.html' %}

<p class="
{% block extra_p_classes %}
  hanging-indent mb-0
{% endblock %}
"></p>

statblocks/templates/statblocks/monster_detail.html
{% extends 'base/base.html' %}
{% load base %}

{% block content %}
  <div class="container mb-5">
    <div class="card" style="width: 40rem">
      {#  <img class="card-img-top" src="{{ monster.image?? }}">#}
      <div class="card-header bg-dark text-white">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <h1 class="card-title">{{ monster.name }}</h1>
            <h6 class="card-subtitle mb-1">
              {{ monster.get_size_display|capfirst }} {{ monster.type }}, {{ monster.get_alignment_display }}
            </h6>
          </div>
          <div>
            <a class="btn btn-lg btn-outline-light" href="{{ monster.get_edit_url }}">
              Edit
            </a>
          </div>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text mb-0">
          <strong>Armor Class</strong>
          {{ monster.armor_class }}{% if monster.armor_kind %} ({{ monster.armor_kind }}){% endif %}
        </p>
        <p class="card-text mb-0">
          <strong>Hit Points</strong>
          {% if monster.hit_points %}
            {{ monster.hit_points }}
          {% else %}
            {{ monster.gen_hp }}
          {% endif %}
          ({{ monster.num_hit_die }}{{ monster.get_hit_die_size_display }}
          {% if monster.con_mod > 0 %}
            + {{ monster.num_hit_die|multiply:monster.con_mod }})
          {% elif monster.con_mod < 0 %}
            - {{ monster.num_hit_die|multiply:monster.con_mod|multiply:-1 }})
          {% endif %}
        </p>
        <p class="card-text mb-0">
          <strong>Speed</strong>
          {{ monster.speed }}
        </p>
        <hr>
        <div class="row">
          <div class="col text-center">
            <strong>STR</strong>
            <br>
            {{ monster.str }} ({% if monster.str_mod > -1 %}+{% endif %}{{ monster.str_mod }})
          </div>
          <div class="col text-center">
            <strong>DEX</strong>
            <br>
            {{ monster.dex }} ({% if monster.dex_mod > -1 %}+{% endif %}{{ monster.dex_mod }})
          </div>
          <div class="col text-center">
            <strong>CON</strong>
            <br>
            {{ monster.con }} ({% if monster.con_mod > -1 %}+{% endif %}{{ monster.con_mod }})
          </div>
          <div class="col text-center">
            <strong>INT</strong>
            <br>
            {{ monster.int }} ({% if monster.int_mod > -1 %}+{% endif %}{{ monster.int_mod }})
          </div>
          <div class="col text-center">
            <strong>WIS</strong>
            <br>
            {{ monster.wis }} ({% if monster.wis_mod > -1 %}+{% endif %}{{ monster.wis_mod }})
          </div>
          <div class="col text-center">
            <strong>CHA</strong>
            <br>
            {{ monster.cha }} ({% if monster.cha_mod > -1 %}+{% endif %}{{ monster.cha_mod }})
          </div>
        </div>
        <hr>
        {% if monster.saving_throws %}
          <p class="card-text mb-0 hanging-indent">
            <strong>Saving Throws</strong>
            {{ monster.saving_throws }}
          </p>
        {% endif %}
        {% if monster.skills %}
          <p class="card-text mb-0 hanging-indent">
            <strong>Skills</strong>
            {{ monster.skills }}
          </p>
        {% endif %}
        {% if monster.damage_vulnerabilities %}
          <p class="card-text mb-0 hanging-indent">
            <strong>Damage Vulnerabilities</strong>
            {{ monster.get_damage_vulnerabilities_display }}
          </p>
        {% endif %}
        {% if monster.damage_resistances %}
          <p class="card-text mb-0 hanging-indent">
            <strong>Damage Resistances</strong>
            {{ monster.get_damage_resistances_display }}
          </p>
        {% endif %}
        {% if monster.damage_immunities %}
          <p class="card-text mb-0 hanging-indent">
            <strong>Damage Immunities</strong>
            {{ monster.get_damage_immunities_display }}
          </p>
        {% endif %}
        {% if monster.condition_immunities %}
          <p class="card-text mb-0 hanging-indent">
            <strong>Condition Immunities</strong>
            {{ monster.get_condition_immunities_display }}
          </p>
        {% endif %}
        <p class="card-text mb-0 hanging-indent">
          <strong>Senses</strong>
          {{ monster.senses }}
        </p>
        <p class="card-text mb-0 hanging-indent">
          <strong>Languages</strong>
          {% if monster.languages %}
            {{ monster.get_languages_display }}
          {% else %}
            &mdash;
          {% endif %}
        </p>
        <p class="card-text mb-0 hanging-indent">
          <strong>Challenge</strong>
          {{ monster.challenge }}
        </p>
        <hr>
        {% for prop in monster.special_properties.all %}
          {% include 'statblocks/statblockbit.html' with object=prop %}
        {% endfor %}
        <h3 class="mt-3 mb-0">
          Actions
        </h3>
        <hr class="mt-0">
        {% for action in monster.actions.all %}
          {% include 'statblocks/action.html' with object=action %}
        {% endfor %}
        {% if monster.legendary_actions.all %}
          <h3 class="mt-3 mb-0">
            Legendary Actions
          </h3>
          <hr class="mt-0 mb-1">
          <p>
            The {{ monster.statblock_generic_name }} can take 3 legendary actions, choosing from the options below.
            Only one legendary action option can be used at a time and only at the end of another
            creature's turn. The {{ monster.statblock_generic_name }} regains spent legendary actions at the start of
            its turn.
          </p>
          {% for legaction in monster.legendary_actions.all %}
            {% include 'statblocks/legendaryaction.html' with object=legaction %}
          {% endfor %}
        {% endif %}
        {% if monster.reactions.all %}
          <h3 class="mt-3 mb-0">
            Reactions
          </h3>
          <hr class="mt-0">
          {% for reaction in monster.reactions.all %}
            {% include 'statblocks/statblockbit.html' with object=reaction %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

statblocks/templates/statblocks/specialproperty.html
{% load base %}

<p class="card-text">
  <strong><em>
    <a class="text-dark" href="{{ object.get_absolute_url }}">
      {{ object.name }}.</a>
  </em></strong>
  {% if monster %}
    <span style="white-space: pre-line;">{{ object.description|replace_generic_monster:monster }}</span>
  {% else %}
    <span style="white-space: pre-line;">{{ object.description }}</span>
  {% endif %}
</p>